import { ConnectorDescriptor } from './types';

// Single source of truth for every data source. Drives the Data sources page
// and, on the backend, the AI evaluation agent. `live: true` means a real
// backend run() is wired up today; the rest are described but not yet fetched.
export const CONNECTORS: readonly ConnectorDescriptor[] = [
  {
    id: 'github',
    name: 'GitHub',
    domain: 'github.com',
    description: 'Repos, stars and contribution history',
    icon: 'simpleGithub',
    color: '#181717',
    group: 'Connected',
    auth: 'none',
    metrics: ['Proof', 'Trajectory'],
    note: 'Free, GitHub API',
    action: 'connected',
    live: true,
  },
  {
    id: 'npm',
    name: 'npm downloads',
    domain: 'npmjs.com',
    description: 'Package download counts over time',
    icon: 'simpleNpm',
    color: '#CB3837',
    group: 'Connected',
    auth: 'none',
    metrics: ['Proof'],
    note: 'Free, no auth',
    action: 'connected',
    live: true,
  },
  {
    id: 'pypi',
    name: 'PyPI stats',
    domain: 'pypi.org',
    description: 'Python package download volume',
    icon: 'simplePypi',
    color: '#3775A9',
    group: 'Connected',
    auth: 'none',
    metrics: ['Proof'],
    note: 'Free, no auth',
    action: 'connected',
    live: true,
  },
  {
    id: 'producthunt',
    name: 'Product Hunt',
    domain: 'producthunt.com',
    description: 'Launches, upvotes and maker activity',
    icon: 'simpleProducthunt',
    color: '#DA552F',
    group: 'Not supported',
    auth: 'unsupported',
    metrics: [],
    note: 'API redacts third-party makers',
    action: 'unsupported',
    live: false,
  },
  {
    id: 'wayback',
    name: 'Wayback Machine',
    domain: 'web.archive.org',
    description: 'Historical snapshots of past sites',
    icon: 'simpleInternetarchive',
    color: '#a92e34',
    group: 'Connected',
    auth: 'none',
    metrics: ['Trajectory'],
    note: 'Free, Internet Archive',
    action: 'connected',
    live: true,
  },
  {
    id: 'arxiv',
    name: 'arXiv',
    domain: 'arxiv.org',
    description: 'Preprints and research authorship',
    icon: 'simpleArxiv',
    color: '#B31B1B',
    group: 'Connected',
    auth: 'none',
    metrics: ['Proof'],
    note: 'Free, no auth',
    action: 'connected',
    live: true,
  },
  {
    id: 'semanticscholar',
    name: 'Semantic Scholar',
    domain: 'semanticscholar.org',
    description: 'Citations and academic influence',
    icon: 'simpleSemanticscholar',
    color: '#1857B6',
    group: 'Connected',
    auth: 'none',
    metrics: ['Proof'],
    note: 'Free, no auth',
    action: 'connected',
    live: true,
  },
  {
    id: 'stackexchange',
    name: 'Stack Exchange',
    domain: 'stackexchange.com',
    description: 'Answers, reputation and expertise',
    icon: 'simpleStackexchange',
    color: '#1E5397',
    group: 'Connected',
    auth: 'none',
    metrics: ['Proof'],
    note: 'Free, optional key',
    action: 'connected',
    live: true,
  },
  {
    id: 'x',
    name: 'X (Twitter)',
    domain: 'x.com',
    description: 'Followers, reach and network signal',
    icon: 'simpleX',
    color: '#000000',
    group: 'Available',
    auth: 'key',
    metrics: ['Gravity', 'Trajectory'],
    note: 'Third-party API, low cost',
    action: 'add-key',
    live: false,
  },
  {
    id: 'handelsregister',
    name: 'Handelsregister',
    domain: 'handelsregister.de',
    description: 'German company filings and officers',
    icon: 'heroBuildingLibrary',
    group: 'Available',
    auth: 'key',
    metrics: ['Proof'],
    note: 'Third-party API, free tier',
    action: 'connect',
    live: false,
  },
  {
    id: 'googlepatents',
    name: 'Google Patents',
    domain: 'patents.google.com',
    description: 'Patent filings and inventorship',
    icon: 'brandGoogle',
    group: 'Available',
    auth: 'key',
    metrics: ['Proof'],
    note: 'BigQuery, free tier',
    action: 'connect',
    live: false,
  },
  {
    id: 'devpost',
    name: 'Devpost',
    domain: 'devpost.com',
    description: 'Hackathon projects and wins',
    icon: 'simpleDevpost',
    color: '#003E54',
    group: 'Available',
    auth: 'none',
    metrics: ['Proof'],
    note: 'Scrape / RSS',
    action: 'connect',
    live: false,
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    domain: 'linkedin.com',
    description: 'Career history and professional network',
    icon: 'brandLinkedin',
    group: 'Manual input',
    auth: 'manual',
    metrics: ['Proof', 'Gravity'],
    note: 'Paste profile (no scraping)',
    action: 'paste',
    live: false,
  },
  {
    id: 'crunchbase',
    name: 'Crunchbase',
    domain: 'crunchbase.com',
    description: 'Funding rounds and company data',
    icon: 'simpleCrunchbase',
    color: '#0288D1',
    group: 'Not supported',
    auth: 'unsupported',
    metrics: [],
    note: 'Enterprise license only',
    action: 'unsupported',
    live: false,
  },
  {
    id: 'evertrace',
    name: 'Evertrace',
    domain: 'evertrace.ai',
    description: 'Early founder detection signals',
    icon: 'brandEvertrace',
    color: '#262626',
    group: 'Not supported',
    auth: 'unsupported',
    metrics: [],
    note: 'Sales-gated',
    action: 'unsupported',
    live: false,
  },
];
