import type { AnchorFounder } from '../model';

// GENERATED by scratchpad/gen_seed.mjs. The calibration ANCHOR SET: known
// founders, some who succeeded and some who did not, spanning the full range
// so percentiles mean something. Every emitted score is z-normalised and turned
// into a percentile against this set ("43rd percentile, sits next to X").
// Curated reference points, not live scores.
export const ANCHORS: readonly AnchorFounder[] = [
  {
    "name": "Patrick Collison",
    "outcome": "success",
    "proof": 96,
    "gravity": 95,
    "trajectory": 84,
    "note": "Stripe, developer-first payments"
  },
  {
    "name": "Guillermo Rauch",
    "outcome": "success",
    "proof": 93,
    "gravity": 90,
    "trajectory": 82,
    "note": "Vercel, prolific open source"
  },
  {
    "name": "Tobias Lütke",
    "outcome": "success",
    "proof": 90,
    "gravity": 88,
    "trajectory": 74,
    "note": "Shopify, engineer-founder"
  },
  {
    "name": "Sid Sijbrandij",
    "outcome": "success",
    "proof": 82,
    "gravity": 84,
    "trajectory": 78,
    "note": "GitLab, open-core"
  },
  {
    "name": "Mitchell Hashimoto",
    "outcome": "success",
    "proof": 95,
    "gravity": 82,
    "trajectory": 76,
    "note": "HashiCorp, deep infra builder"
  },
  {
    "name": "Dylan Field",
    "outcome": "success",
    "proof": 80,
    "gravity": 86,
    "trajectory": 80,
    "note": "Figma, design tooling"
  },
  {
    "name": "Vitalik Buterin",
    "outcome": "success",
    "proof": 92,
    "gravity": 93,
    "trajectory": 82,
    "note": "Ethereum, research-led"
  },
  {
    "name": "Evan You",
    "outcome": "success",
    "proof": 91,
    "gravity": 84,
    "trajectory": 70,
    "note": "Vue, Vite; solo-to-team OSS"
  },
  {
    "name": "Sindre Sorhus",
    "outcome": "success",
    "proof": 88,
    "gravity": 80,
    "trajectory": 66,
    "note": "Full-time open source at scale"
  },
  {
    "name": "Peter Steinberger",
    "outcome": "success",
    "proof": 89,
    "gravity": 83,
    "trajectory": 88,
    "note": "PSPDFKit (Vienna); big second-act momentum"
  },
  {
    "name": "Anthony Fu",
    "outcome": "success",
    "proof": 84,
    "gravity": 78,
    "trajectory": 79,
    "note": "Vite / Nuxt ecosystem maintainer"
  },
  {
    "name": "David Cramer",
    "outcome": "success",
    "proof": 85,
    "gravity": 72,
    "trajectory": 68,
    "note": "Sentry, developer tooling"
  },
  {
    "name": "Clement Delangue",
    "outcome": "success",
    "proof": 78,
    "gravity": 90,
    "trajectory": 84,
    "note": "Hugging Face; community gravity"
  },
  {
    "name": "Georgi Gerganov",
    "outcome": "success",
    "proof": 90,
    "gravity": 79,
    "trajectory": 92,
    "note": "llama.cpp / ggml; explosive recent slope"
  },
  {
    "name": "Robert Nishihara",
    "outcome": "success",
    "proof": 84,
    "gravity": 74,
    "trajectory": 76,
    "note": "Anyscale / Ray; research to product"
  },
  {
    "name": "Paul Copplestone",
    "outcome": "success",
    "proof": 80,
    "gravity": 75,
    "trajectory": 82,
    "note": "Supabase, open-source Firebase"
  },
  {
    "name": "Zeno Rocha",
    "outcome": "success",
    "proof": 74,
    "gravity": 76,
    "trajectory": 74,
    "note": "Resend; DX + audience"
  },
  {
    "name": "Alexandr Wang",
    "outcome": "success",
    "proof": 66,
    "gravity": 89,
    "trajectory": 85,
    "note": "Scale AI; young, high pull"
  },
  {
    "name": "Melanie Perkins",
    "outcome": "success",
    "proof": 62,
    "gravity": 87,
    "trajectory": 78,
    "note": "Canva; persistence + distribution"
  },
  {
    "name": "Daniel Dines",
    "outcome": "success",
    "proof": 68,
    "gravity": 80,
    "trajectory": 70,
    "note": "UiPath; long build then breakout"
  },
  {
    "name": "Christian Reber",
    "outcome": "success",
    "proof": 70,
    "gravity": 82,
    "trajectory": 74,
    "note": "Pitch / Wunderlist (Berlin)"
  },
  {
    "name": "Johannes Reck",
    "outcome": "success",
    "proof": 60,
    "gravity": 84,
    "trajectory": 76,
    "note": "GetYourGuide (Berlin)"
  },
  {
    "name": "Hanno Renner",
    "outcome": "success",
    "proof": 64,
    "gravity": 81,
    "trajectory": 83,
    "note": "Personio (Munich); HR SaaS"
  },
  {
    "name": "Erik Muttersbach",
    "outcome": "success",
    "proof": 82,
    "gravity": 70,
    "trajectory": 80,
    "note": "Forto (Berlin); technical logistics"
  },
  {
    "name": "Amjad Masad",
    "outcome": "success",
    "proof": 80,
    "gravity": 78,
    "trajectory": 72,
    "note": "Replit; builder + community"
  },
  {
    "name": "Aravind Srinivas",
    "outcome": "success",
    "proof": 72,
    "gravity": 70,
    "trajectory": 88,
    "note": "Perplexity; research-to-founder"
  },
  {
    "name": "Theo Browne",
    "outcome": "mixed",
    "proof": 66,
    "gravity": 74,
    "trajectory": 68,
    "note": "Ping / t3; audience-led"
  },
  {
    "name": "Lee Robinson",
    "outcome": "success",
    "proof": 68,
    "gravity": 76,
    "trajectory": 66,
    "note": "DX leader; strong distribution"
  },
  {
    "name": "Travis Fischer",
    "outcome": "mixed",
    "proof": 72,
    "gravity": 66,
    "trajectory": 74,
    "note": "Agentic AI OSS; indie momentum"
  },
  {
    "name": "Mckay Wrigley",
    "outcome": "mixed",
    "proof": 70,
    "gravity": 72,
    "trajectory": 78,
    "note": "AI apps; ships fast in public"
  },
  {
    "name": "Shawn Wang",
    "outcome": "success",
    "proof": 60,
    "gravity": 72,
    "trajectory": 64,
    "note": "DX / Latent Space; learn-in-public"
  },
  {
    "name": "Pim de Witte",
    "outcome": "success",
    "proof": 64,
    "gravity": 58,
    "trajectory": 70,
    "note": "Medal; product-led"
  },
  {
    "name": "Ian Storm Taylor",
    "outcome": "mixed",
    "proof": 78,
    "gravity": 62,
    "trajectory": 55,
    "note": "Segment / Slate; strong builder"
  },
  {
    "name": "Emad Mostaque",
    "outcome": "mixed",
    "proof": 70,
    "gravity": 88,
    "trajectory": 60,
    "note": "Stability AI; attention, governance issues"
  },
  {
    "name": "an early finance-ML founder",
    "display": "an early finance-ML founder",
    "outcome": "success",
    "proof": 68,
    "gravity": 50,
    "trajectory": 76,
    "note": "Quant/ML background, exceptional fit, network still forming; later raised a seed"
  },
  {
    "name": "an early ML-infra founder",
    "display": "an early ML-infra founder",
    "outcome": "success",
    "proof": 66,
    "gravity": 48,
    "trajectory": 78,
    "note": "Strong build record, thin public network"
  },
  {
    "name": "a quant-turned-founder",
    "display": "a quant-turned-founder",
    "outcome": "success",
    "proof": 64,
    "gravity": 46,
    "trajectory": 70,
    "note": "Deep domain, early on distribution"
  },
  {
    "name": "a repeat second-time founder",
    "display": "a repeat second-time founder",
    "outcome": "success",
    "proof": 62,
    "gravity": 58,
    "trajectory": 60,
    "note": "Credible, mid pull, steady"
  },
  {
    "name": "a research-heavy PhD founder",
    "display": "a research-heavy PhD founder",
    "outcome": "mixed",
    "proof": 68,
    "gravity": 44,
    "trajectory": 60,
    "note": "Papers, slow to ship product"
  },
  {
    "name": "an indie AI-app founder",
    "display": "an indie AI-app founder",
    "outcome": "mixed",
    "proof": 56,
    "gravity": 50,
    "trajectory": 74,
    "note": "Ships fast in public, unproven at scale"
  },
  {
    "name": "a technical hackathon winner",
    "display": "a technical hackathon winner",
    "outcome": "mixed",
    "proof": 58,
    "gravity": 40,
    "trajectory": 74,
    "note": "Wins, exceptional fit, not yet scaled"
  },
  {
    "name": "a promising student founder",
    "display": "a promising student founder",
    "outcome": "success",
    "proof": 58,
    "gravity": 40,
    "trajectory": 76,
    "note": "Early, steep slope, great founder-market-fit"
  },
  {
    "name": "a solo devtools founder",
    "display": "a solo devtools founder",
    "outcome": "mixed",
    "proof": 60,
    "gravity": 38,
    "trajectory": 66,
    "note": "Shipped real tools, no audience yet"
  },
  {
    "name": "a domain-expert career-switcher",
    "display": "a domain-expert career-switcher",
    "outcome": "mixed",
    "proof": 50,
    "gravity": 40,
    "trajectory": 56,
    "note": "Deep domain, new to building"
  },
  {
    "name": "a design-led founder",
    "display": "a design-led founder",
    "outcome": "mixed",
    "proof": 48,
    "gravity": 54,
    "trajectory": 60,
    "note": "Product taste, light engineering"
  },
  {
    "name": "a bootstrapped SaaS founder",
    "display": "a bootstrapped SaaS founder",
    "outcome": "success",
    "proof": 52,
    "gravity": 46,
    "trajectory": 58,
    "note": "Steady, unflashy, real revenue"
  },
  {
    "name": "a community-first founder",
    "display": "a community-first founder",
    "outcome": "mixed",
    "proof": 44,
    "gravity": 62,
    "trajectory": 58,
    "note": "Audience ahead of product"
  },
  {
    "name": "a first-time fintech founder",
    "display": "a first-time fintech founder",
    "outcome": "mixed",
    "proof": 55,
    "gravity": 42,
    "trajectory": 62,
    "note": "Early traction, thin evidence"
  },
  {
    "name": "a bootcamp-to-founder",
    "display": "a bootcamp-to-founder",
    "outcome": "failed",
    "proof": 40,
    "gravity": 30,
    "trajectory": 52,
    "note": "Enthusiasm ahead of shipped evidence"
  },
  {
    "name": "a stalled first-timer",
    "display": "a stalled first-timer",
    "outcome": "failed",
    "proof": 40,
    "gravity": 34,
    "trajectory": 38,
    "note": "Momentum died after v1"
  },
  {
    "name": "an idea-stage first timer",
    "display": "an idea-stage first timer",
    "outcome": "failed",
    "proof": 30,
    "gravity": 28,
    "trajectory": 42,
    "note": "No shipped proof, low momentum"
  },
  {
    "name": "an all-pitch no-ship founder",
    "display": "an all-pitch no-ship founder",
    "outcome": "failed",
    "proof": 30,
    "gravity": 58,
    "trajectory": 40,
    "note": "Pitch ahead of proof"
  },
  {
    "name": "Adam Neumann",
    "outcome": "failed",
    "proof": 44,
    "gravity": 92,
    "trajectory": 50,
    "note": "WeWork; huge gravity, governance red flags"
  },
  {
    "name": "Elizabeth Holmes",
    "outcome": "failed",
    "proof": 20,
    "gravity": 90,
    "trajectory": 30,
    "note": "Theranos; overclaiming, capped by gate"
  },
  {
    "name": "Trevor Milton",
    "outcome": "failed",
    "proof": 22,
    "gravity": 78,
    "trajectory": 28,
    "note": "Nikola; overclaiming"
  },
  {
    "name": "Charlie Javice",
    "outcome": "failed",
    "proof": 30,
    "gravity": 74,
    "trajectory": 34,
    "note": "Frank; fabricated metrics"
  }
];

export const ANCHOR_PROOF = ANCHORS.map((a) => a.proof);
export const ANCHOR_GRAVITY = ANCHORS.map((a) => a.gravity);
export const ANCHOR_TRAJECTORY = ANCHORS.map((a) => a.trajectory);
